name: Firebase Code Check Pipeline

on:
  push:
    branches:
      - main # Trigger the pipeline on pushes to the main branch

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Authenticate with Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: echo "Authenticated with Firebase"

      - name: Run Tests or Code Linting
        run: npm test
